#define HYPERVISOR_BASE 	0x100000000ULL /* @4GiB */
#define JAILHOUSE_RESERVED_SIZE 0x200000000ULL /* 8GiB */
#define JAILHOUSE_RESERVED_END	(HYPERVISOR_BASE + JAILHOUSE_RESERVED_SIZE)
#define HYPERVISOR_SIZE		0x000600000ULL /* 6MiB */
#define HYPERVISOR_END		(HYPERVISOR_BASE + HYPERVISOR_SIZE)

#define IVSHMEM_BASE		HYPERVISOR_END
#define IVSHMEM_SIZE		0x100000ULL /* 1MiB */

#define INMATE_BASE		(IVSHMEM_BASE + IVSHMEM_SIZE)
#define INMATE_SIZE		(JAILHOUSE_RESERVED_END - INMATE_BASE) /* = 8GiB - 6MiB - 1MiB */
