#define HYPERVISOR_BASE 	0x100000000ULL
#define JAILHOUSE_RESERVED_SIZE 0x200000000ULL
#define JAILHOUSE_RESERVED_END	(HYPERVISOR_BASE + JAILHOUSE_RESERVED_SIZE)
#define HYPERVISOR_SIZE		0x000600000ULL
#define HYPERVISOR_END		(HYPERVISOR_BASE + HYPERVISOR_SIZE)

#define IVSHMEM_SIZE		0xff000ULL
#define IVSHMEM_BASE		(JAILHOUSE_RESERVED_END - IVSHMEM_SIZE)

#define INMATE_BASE		HYPERVISOR_END
#define INMATE_SIZE		(IVSHMEM_BASE - INMATE_BASE)
