#
# Jailhouse, a Linux-based partitioning hypervisor
#
# Copyright (c) Siemens AG, 2020
#
# Authors:
#  Jan Kiszka <jan.kiszka@siemens.com>
#
# This work is licensed under the terms of the GNU GPL, version 2.  See
# the COPYING file in the top-level directory.
#

-include $(GEN_CONFIG_MK)

always-y := lib.a

lib-y := entry.o exception.o setup.o dbg-write.o control.o ivshmem.o irqchip.o
lib-y += paging.o pci.o plic.o traps.o lib.o
